version: "3.9"

services:

  amnod-testnet:
    env_file: .env
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        NETWORK: testnet
    container_name: amnod-testnet
    ports: 
      - "18888:8888"
      - "19806:9806"
      - "19555:9555"
    volumes:
      - /opt/data/amax_testnet/:/opt/data/amax/