version: "3.9"

services:

  amnod-${NETWORK}:
    image: armoniax/amnod:${AMNOD_IMG_VER}
    env_file: .env
    # build:
    #   context: ../
    #   dockerfile: Dockerfile
    #   args:
    #     NETWORK: mainnet
    container_name: amnod-${NETWORK}
    working_dir: /opt/data/amax_${NETWORK}
    entrypoint: ["./bin/start.sh", "$PARAMs"]
    ports: 
      - "${RPC_PORT}:8888"
      - "${P2P_PORT}:9876"
      - "${HISTORY_WS_PORT}:9555"
    volumes:
      - /opt/data/amax_${NETWORK}/:/opt/data/amax_${NETWORK}/