version: "3.9"

services:

  amnod-mainnet:
    env_file: .env
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        NETWORK: mainnet
    container_name: amnod-mainnet
    ports: 
      - "8888:8888"
      - "9806:9806"
      - "9555:9555"
    volumes:
      - /opt/data/amax_mainnet/:/opt/data/amax/