version: "3.9"

services:

  amnod-devnet:
    env_file: .env
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        NETWORK: devnet
    container_name: amnod-devnet
    ports: 
      - "28888:8888"
      - "29806:9806"
      - "29555:9555"
    volumes:
      - /opt/data/amax_devnet/:/opt/data/amax_devnet/