version: "3"

services:
  
  mongodb:
    image: mongo:4.0
    container_name: expmongo
    restart: always
    volumes:
      - /opt/data/mongo:/data/db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Amax123
      MONGO_INITDB_DATABASE: AMAXExp

  frontend:
    build:
      context: ./docker
      dockerfile: Dockerfile.web
    container_name: expweb
    ports: 
      - 8080:80
    restart: always

  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile.srv
    container_name: expsrv
    ports: 
      - 3039:3039
    restart: always
