version: "3"

services:
  
  mongodb:
    image: mongo:4.2
    container_name: expmongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_PSWD}
    ports:
      - 27017:27017
    volumes:
      - /opt/data/mongo:/data/db

  frontend:
    build:
      context: ./docker
      dockerfile: Dockerfile.web
    container_name: expweb
    ports: 
      - 8080:80
    restart: always

  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile.srv
    container_name: expsrv
    ports: 
      - 3039:3039
    restart: always
