version: "3.9"

services:
  amnod:
    image: armoniax/amnod:${AMNOD_IMG_VER}
    container_name: amnod-${NET}
    working_dir: /opt/data/amax_${NET}
    entrypoint: ["./bin/start.sh", "${NET}", "$PARAMs"]
    ports: 
      - "${RPC_PORT}:8888"
      - "${P2P_PORT}:9876"
      - "${HIST_WS_PORT}:9555"
    volumes:
      - /opt/data/amax_${NET}/:/opt/data/amax_${NET}/