version: "3.9"

services:

  amnod-devnet:
    env_file: .devnet.env
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NETWORK: devnet
    container_name: amnod-devnet
    ports: 
      - "8888:8888"
      - "9806:9806"
    volumes:
      - /opt/data/amax_devnet/data:/opt/amax/data
      - /opt/data/amax_devnet/logs:/opt/amax/logs