version: "3.9"

services:
  "amnod-$NET":
    image: armoniax/amnod:${AMNOD_IMG_VER}
    container_name: amnod-${NET}
    working_dir: "${NODE_HOME}/amax_${NET}"
    entrypoint: ["./bin/start.sh", "$NODE_HOME", "$NET", "$PARAMs"]
    ports: 
      - "${RPC_PORT}:8888"
      - "${P2P_PORT}:9876"
      - "${HIST_WS_PORT}:9555"
    volumes:
      - ${NODE_HOME}/amax_$NET/:${NODE_HOME}/amax_${NET}/
    dns:
      - 114.114.114.114
      - 8.8.8.8