version: "3.9"

services:

  amnod-testnet:
    env_file: .testnet.env
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NETWORK: testnet
    container_name: amnod-testnet
    ports: 
      - "8888:8888"
      - "9806:9806"
    volumes:
      - /opt/data/amax_testnet/data:/opt/amax/data
      - /opt/data/amax_testnet/logs:/opt/amax/logs