version: "3.9"

services:

  amnod-testnet:
    env_file: .testnet.env
    build: .
    container_name: amnod-testnet
    args:
      - NETWORK: ${NETWORK}
    ports: 
      - "8888:8888"
      - "9806:9806"
    volumes:
      - /opt/data/amax_mainnet/data:/opt/amax/data
      - /opt/data/amax_mainnet/logs:/opt/amax/logs

  amnod-devnet:
    env_file: .devnet.env
    build: .
    container_name: amnod-devnet
    args:
      - NETWORK: ${NETWORK}
    ports: 
      - "8888:8888"
      - "9806:9806"
    volumes:
      - /opt/data/amax_mainnet/data:/opt/amax/data
      - /opt/data/amax_mainnet/logs:/opt/amax/logs

  amnod-mainnet:
    env_file: .mainnet.env
    build: .
    container_name: amnod-mainnet
    args:
      - NETWORK: ${NETWORK}  
    ports: 
      - "8888:8888"
      - "9806:9806"
    volumes:
      - /opt/data/amax_mainnet/data:/opt/amax/data
      - /opt/data/amax_mainnet/logs:/opt/amax/logs