version: "3.9"

services:

  amnod-mainnet:
    env_file: .mainnet.env
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NETWORK: mainnet
    container_name: amnod-mainnet
    ports: 
      - "8888:8888"
      - "9806:9806"
    volumes:
      - /opt/data/amax_mainnet/data:/opt/amax/data
      - /opt/data/amax_mainnet/logs:/opt/amax/logs