version: "3.9"

services:

  amaxnode:
    env_file: ${ENV_FILE}
    build:
        context: ./docker
        dockerfile: Dockerfile
    ports: 
      - "8888:8888"
      - "9806:9806"
    volumes:
      - /opt/data/amax_mainnet/data:/opt/amax/data
      - /opt/data/amax_mainnet/logs:/opt/amax/logs